=== goldstack/cognito-nodejs-template/packages/user-management-1/schemas/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ThisPackage",
  "definitions": {
    "ThisPackage": {
      "type": "object",
      "properties": {
        "template": {
          "$ref": "#/definitions/Template"
        },
        "templateVersion": {
          "$ref": "#/definitions/TemplateVersion"
        },
        "name": {
          "$ref": "#/definitions/Name"
        },
        "configuration": {
          "$ref": "#/definitions/ThisPackageConfiguration"
        },
        "deployments": {
          "$ref": "#/definitions/UserManagementDeployments"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "$schema",
        "configuration",
        "deployments",
        "name",
        "template",
        "templateVersion"
      ],
      "additionalProperties": false,
      "description": "A cognito configuration.",
      "title": "User Management Package"
    },
    "Template": {
      "type": "string",
      "description": "Name of the template used for creating this package.",
      "title": "Template",
      "pattern": "^[^\\s]*$"
    },
    "TemplateVersion": {
      "type": "string",
      "description": "Latest template version that was applied to this package.",
      "title": "Template Version"
    },
    "Name": {
      "type": "string",
      "description": "Name of this package.",
      "title": "Package Name"
    },
    "ThisPackageConfiguration": {
      "type": "object",
      "properties": {},
      "description": "User Management Configuration",
      "title": "User Management Configuration"
    },
    "UserManagementDeployments": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ThisDeployment"
      },
      "description": "Places where cognito should be deployed to.",
      "title": "Deployments"
    },
    "ThisDeployment": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/DeploymentName"
        },
        "configuration": {
          "$ref": "#/definitions/ThisDeploymentConfiguration"
        },
        "terraformVariables": {
          "$ref": "#/definitions/TerraformVariables"
        },
        "tfStateKey": {
          "$ref": "#/definitions/TerraformStateKey"
        },
        "tfVersion": {
          "$ref": "#/definitions/TerraformVersion"
        },
        "awsRegion": {
          "$ref": "#/definitions/AWSDeploymentRegion"
        },
        "awsUser": {
          "$ref": "#/definitions/AWSUserName"
        }
      },
      "required": ["awsRegion", "awsUser", "configuration", "name"]
    },
    "DeploymentName": {
      "type": "string",
      "description": "Identifier for this deployment. No spaces allowed in name.",
      "title": "Deployment Name",
      "pattern": "^[^\\s]*$"
    },
    "ThisDeploymentConfiguration": {
      "type": "object",
      "properties": {
        "userPoolName": {
          "$ref": "#/definitions/UserPoolName"
        },
        "hostedZoneDomain": {
          "$ref": "#/definitions/HostedZoneDomain"
        },
        "cognitoDomain": {
          "$ref": "#/definitions/CognitoDomain"
        },
        "cookieDomain": {
          "$ref": "#/definitions/CookieDomain"
        },
        "cookieSameSite": {
          "$ref": "#/definitions/CookieSameSite"
        },
        "callbackUrl": {
          "$ref": "#/definitions/CallbackUrl"
        },
        "deletionProtection": {
          "$ref": "#/definitions/DeletionProtection"
        }
      },
      "required": [
        "userPoolName",
        "hostedZoneDomain",
        "cognitoDomain",
        "cookieDomain",
        "cookieSameSite",
        "callbackUrl"
      ]
    },
    "UserPoolName": {
      "type": "string",
      "description": "The name of the Cognito user pool.",
      "title": "User Pool Name",
      "pattern": "^[A-Za-z0-9-]*$"
    },
    "HostedZoneDomain": {
      "type": "string",
      "description": "The domain name of the Route 53 hosted zone that the cognito domain should be added to.",
      "title": "Hosted Zone Domain",
      "pattern": "^[^\\s]*"
    },
    "CognitoDomain": {
      "type": "string",
      "description": "The domain where Cognito will be deployed to",
      "title": "Cognito Domain",
      "pattern": "^[^\\s]*"
    },
    "CookieDomain": {
      "type": "string",
      "description": "The domain that cookies will be set for. Consider starting the domain with a '.' if API hosted on subdomain, e.g. set to '.yourdomain.com' if your API is hosted on 'api.yourdomain.com'.",
      "title": "Cookie Domain",
      "pattern": "^[^\\s]*"
    },
    "CookieSameSite": {
      "type": "string",
      "description": "Value for the 'SameSite' attribute for the cookie. 'None' is recommend if your API is hosted on a different subdomain.",
      "title": "Cookie SameSite",
      "pattern": "^[^\\s]*"
    },
    "CallbackUrl": {
      "type": "string",
      "description": "URL that users should be redirected to after a successful login.",
      "title": "Callback URL",
      "pattern": "^[^\\s]*"
    },
    "DeletionProtection": {
      "type": "boolean",
      "description": "When active, prevents accidental deletion of the user pool. Before you can delete a user pool that you have protected against deletion, you must deactivate this feature.",
      "title": "Deletion Protection",
      "default": false
    },
    "TerraformVariables": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/TerraformVariable"
      },
      "description": "Define which of the deployment variables will be made available for terraform.",
      "title": "Terraform Variables"
    },
    "TerraformVariable": {
      "type": "string",
      "description": "Name of the property that should be converted into a Terraform variable.",
      "title": "Terraform Variable"
    },
    "TerraformStateKey": {
      "type": "string",
      "description": "Key used for Terraform state persisted in Terraform state bucket.\n\nWill be auto-generated upon first deployment if not provided.",
      "title": "Terraform State Key"
    },
    "TerraformVersion": {
      "type": "string",
      "description": "Version of Terraform that the remote state for this deployment was created with.\n\nGo to the next version using `yarn infra upgrade [deploymentName] [targetVersion]`. Note that Terraform versions should only be increased one at a time, so for instance you can go from v0.12 to v0.13 but not from v0.12 to v0.14.",
      "default": "1.10"
    },
    "AWSDeploymentRegion": {
      "type": "string",
      "enum": [
        "us-east-1",
        "us-east-2",
        "us-west-1",
        "us-west-2",
        "af-south-1",
        "ap-east-1",
        "ap-south-1",
        "ap-northeast-3",
        "ap-northeast-2",
        "ap-southeast-1",
        "ap-southeast-2",
        "ap-northeast-1",
        "ca-central-1",
        "eu-central-1",
        "eu-west-1",
        "eu-west-2",
        "eu-south-1",
        "eu-west-3",
        "eu-north-1",
        "me-south-1",
        "sa-east-1"
      ],
      "description": "AWS region that infrastructure should be deployed to.",
      "title": "AWS Deployment Region"
    },
    "AWSUserName": {
      "type": "string",
      "description": "Name of the AWS user that is used to perform the deployment.",
      "title": "AWS User Name"
    }
  }
}

=== goldstack/cognito-nodejs-template/packages/user-management-1/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "user-management-1",
  "template": "user-management",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsUser": "goldstack-dev",
      "awsRegion": "us-west-2",
      "configuration": {
        "cognitoDomain": "auth-integration-1776029022930.dev.goldstack.party",
        "userPoolName": "integration-pool-1776029022930",
        "hostedZoneDomain": "dev.goldstack.party",
        "cookieDomain": ".dev.goldstack.party",
        "cookieSameSite": "None",
        "callbackUrl": "https://ssr.examples.templates.dev.goldstack.party"
      },
      "tfStateKey": "user-management-1-prod-d8b73a4144fc91a9aad9.tfstate"
    }
  ]
}
